#ifndef STM32F401_ACQUISITION_H
#define STM32F401_ACQUISITION_H

/* Include the portable acquisition calibration and measurement processor. */
#include "guardian_acquisition.h"

/* Include fixed-width integer types for clocks, rates and diagnostics. */
#include <stdint.h>

/* Define the default ADC scan-frame trigger frequency. */
#define GUARDIAN_STM32F401_ACQUISITION_DEFAULT_SAMPLE_RATE_HZ ((uint32_t)4000UL)

/* Define the lowest supported deterministic ADC scan-frame rate. */
#define GUARDIAN_STM32F401_ACQUISITION_MIN_SAMPLE_RATE_HZ ((uint32_t)100UL)

/* Define the highest supported reference ADC scan-frame rate. */
#define GUARDIAN_STM32F401_ACQUISITION_MAX_SAMPLE_RATE_HZ ((uint32_t)10000UL)

/* Define the reference TIM3 counter frequency used for RPM capture. */
#define GUARDIAN_STM32F401_RPM_TIMER_HZ ((uint32_t)10000UL)

/* Define the maximum RPM age before the measurement is marked stale. */
#define GUARDIAN_STM32F401_RPM_STALE_MS ((uint32_t)2000UL)

/* Store explicit STM32 acquisition configuration and external-sensor calibration. */
typedef struct
{
    /* Store the TIM2-driven ADC scan-frame rate. */
    uint32_t sample_rate_hz;

    /* Store the number of sensor pulses generated by one shaft revolution. */
    uint16_t rpm_pulses_per_revolution;

    /* Store the NVIC priority used by DMA2 Stream0. */
    uint32_t dma_irq_priority;

    /* Store the NVIC priority used by TIM3 input capture. */
    uint32_t rpm_irq_priority;

    /* Store the NVIC priority used by ADC overrun detection. */
    uint32_t adc_irq_priority;

    /* Store explicit raw-to-engineering-unit calibration. */
    guardian_acquisition_calibration_t calibration;
} guardian_stm32f401_acquisition_config_t;

/* Store hardware acquisition diagnostics. */
typedef struct
{
    /* Count completed DMA target buffers. */
    uint32_t dma_blocks_completed;

    /* Count completed buffers replaced before foreground processing. */
    uint32_t dma_blocks_dropped;

    /* Count DMA transfer or direct-mode failures. */
    uint32_t dma_errors;

    /* Count ADC overrun events. */
    uint32_t adc_overruns;

    /* Count successful acquisition stream recoveries. */
    uint32_t recoveries;

    /* Count valid TIM3 rising-edge captures. */
    uint32_t rpm_edges;
} guardian_stm32f401_acquisition_stats_t;

/* Fill one configuration with documented M6 reference defaults and factory calibration. */
void guardian_stm32f401_acquisition_default_config(
    guardian_stm32f401_acquisition_config_t *config);

/* Configure TIM2-triggered ADC1 scan, DMA2 double buffer and TIM3 RPM capture. */
int guardian_stm32f401_acquisition_init(
    const guardian_stm32f401_acquisition_config_t *config);


/* Process at most one completed DMA block and optionally export the calibrated M7 signal block. */
int guardian_stm32f401_acquisition_poll_ex(
    guardian_machine_measurements_t *measurements,
    guardian_acquisition_signal_block_t *signal_block);

/* Process at most one completed DMA block and return one fresh measurement snapshot. */
int guardian_stm32f401_acquisition_poll(
    guardian_machine_measurements_t *measurements);

/* Advance RPM staleness tracking by one millisecond. */
void guardian_stm32f401_acquisition_tick_1ms(void);

/* Return a copy of hardware acquisition diagnostics. */
guardian_stm32f401_acquisition_stats_t guardian_stm32f401_acquisition_stats(void);

/* Service DMA2 Stream0 completion and transfer-error events. */
void guardian_stm32f401_acquisition_dma_irq_handler(void);

/* Service ADC1 overrun events that require acquisition recovery. */
void guardian_stm32f401_acquisition_adc_irq_handler(void);

/* Service TIM3 channel-1 RPM input-capture events. */
void guardian_stm32f401_acquisition_tim3_irq_handler(void);

#endif
